In [1]:
 import pandas as pd

In [2]:
bricks = {"country": ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
         "capital": ['Brazilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
         "area": [8.516, 17.100, 3.286, 9.597, 1.221],
         "population": [200.40, 143.50, 1252.00, 1357.00, 52.98]}

In [3]:
bricks_df = pd.DataFrame(bricks)
bricks_df

        country    capital    area  population
0        Brazil   Brazilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [5]:
bricks_csv = pd.read_csv('./dataset/bricks.csv')
bricks_csv

  Unnamed: 0       country    capital    area  population
0         BR        Brazil   Brasilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98

In [7]:
bricks_csv = pd.read_csv('./dataset/bricks.csv', index_col=0)
bricks_csv

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [9]:
bricks_csv[0:2]

   country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5

In [11]:
bricks_csv

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [12]:
bricks_csv.loc['RU'] #rows as pandas series

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

In [15]:
bricks_csv.loc[['RU']]

   country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [16]:
bricks_csv.loc[['RU','CH']] # specific rows

   country  capital    area  population
RU  Russia   Moscow  17.100       143.5
CH   China  Beijing   9.597      1357.0

In [17]:
bricks_csv.loc[['RU','CH'], ['country', 'population']] # specific rows and columns

   country  population
RU  Russia       143.5
CH   China      1357.0

In [18]:
cars_csv = pd.read_csv('./dataset/cars.csv')
cars_csv

  Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JPN           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

### Aggregation

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt